# Generated by Django 5.0.6 on 2024-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('idade', models.CharField(choices=[('18+', 'Maior idade'), ('18-', 'Menos idade')], max_length=4)),
            ],
        ),
    ]
