# Generated by Django 5.0.6 on 2024-06-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_moveis', models.CharField(max_length=100)),
                ('valor_moveis', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vestuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vestuario', models.CharField(max_length=100)),
                ('valor_vestuario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
