# Generated by Django 5.0.6 on 2024-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eletronicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_eletro', models.CharField(max_length=100)),
                ('valor_eletro', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_compraE', models.DateField()),
                ('foto_eletro', models.ImageField(upload_to='foto_eletro/')),
            ],
        ),
        migrations.CreateModel(
            name='Moveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_moveis', models.CharField(max_length=100)),
                ('valor_moveis', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_compraM', models.DateField()),
                ('foto_moveis', models.ImageField(upload_to='foto_moveis/')),
            ],
        ),
        migrations.CreateModel(
            name='Vestuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vestuario', models.CharField(max_length=100)),
                ('valor_vestuario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_compraV', models.DateField()),
                ('foto_vestuario', models.ImageField(upload_to='foto_vestuario/')),
            ],
        ),
    ]
